on: [ push, pull_request ]
jobs:
  build:
    name: Unit and E2E Tests
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install vcpkg packages
        run: |
          cd OpenCppCoverage
          vcpkg install
          vcpkg integrate install
          cd ..
          cd lcov
          vcpkg install
          vcpkg integrate install
          cd ../lcovTest
          vcpkg install
          vcpkg integrate install
          cd ..
      - name: Build solution
        run: |
          msbuild /m ./OpenCppCoverage/CppCoverage.slnx /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v143
          msbuild /m ./OpenCppCoverage/CppCoverage.slnx /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143
          nuget restore covlcov.slnx
          msbuild /m covlcov.slnx /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v143
          msbuild /m covlcov.slnx /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Run unit tests
        id: tests
        continue-on-error: true
        run: |
          cd lcovTest
          .\..\x64\Debug\lcovTest.exe
          cd ..

      - name: Generate coverage report
        continue-on-error: true
        run: |
          cd lcovTest
          & ".\..\OpenCppCoverage\x64\Release\OpenCppCoverage.exe" `
            --sources "lcov" `
            --modules "lcov.dll" `
            --excluded_sources "*vcpkg_installed*" `
            --excluded_sources "*OpenCppCoverage*" `
            --excluded_modules "*Plugins\Exporter\lcov.dll" `
            --export_type=html:"../codecov/html" `
            --export_type=lcov:"../codecov/coverage.info" `
            --cover_children `
            -- ".\..\x64\Release\lcovTest.exe"
          cd ..

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./codecov/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Failure Check
        if: steps.tests.outcome == 'failure'
        run: exit 1

      - name: Check if release file exists
        id: check_file
        run: |
          $file = "./x64/Release/lcov.dll"
          if (Test-Path $file) {
              Write-Host "File exists."
              "exists=true" >> $env:GITHUB_OUTPUT
          }
          else {
              Write-Host "File NOT found."
              "exists=false" >> $env:GITHUB_OUTPUT
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' &&
          startsWith(github.ref, 'refs/tags/v') &&
          steps.check_file.outputs.exists == 'true'
        with:
          files: ./x64/Release/lcov.dll
