on: [ push, pull_request ]
jobs:
  build:
    name: Unit and E2E Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install vcpkg packages
        run: |
          cd OpenCppCoverage
          vcpkg install
          vcpkg integrate install
          cd ..
          cd lcov
          vcpkg install
          vcpkg integrate install
          cd ../lcovTest
          vcpkg install
          vcpkg integrate install
          cd ..
      - name: Build solution
        run: |
          msbuild /m ./OpenCppCoverage/CppCoverage.slnx /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v143
          msbuild /m ./OpenCppCoverage/CppCoverage.slnx /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143
          nuget restore covlcov.slnx
          msbuild /m covlcov.slnx /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v143
          msbuild /m covlcov.slnx /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Run unit tests
        continue-on-error: true
        run: |
          cd lcovTest
          .\..\x64\Debug\lcovTest.exe
          cd ..

      - name: Generate coverage report
        continue-on-error: true
        run: |
          cd lcovTest
          & ".\..\OpenCppCoverage\x64\Release\OpenCppCoverage.exe" `
            --sources "lcov" `
            --modules "lcov.dll" `
            --excluded_sources "*vcpkg_installed*" `
            --excluded_sources "*OpenCppCoverage*" `
            --excluded_modules "*Plugins\Exporter\lcov.dll" `
            --export_type=html:"../codecov/html" `
            --export_type=lcov:"../codecov/coverage.info" `
            --cover_children `
            -- ".\..\x64\Release\lcovTest.exe"
          cd ..

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./codecov/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Failure Check
        if: always()
        run: |
          if [[ "${{ steps.tests.outcome }}" == "failure" ]]; then
            echo "Tests failed"
            exit 1
          fi
